import { Drawer, Menu } from "antd";
import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import App from "./Antd";
import DrawerComp from "./Drawer";
import Hero from "./Hero";
import Socials from "./Socials";
import styles from "../styles/Home.module.css";
import { useMediaQuery } from "react-responsive";
import { useSelector } from "react-redux";
import ToTop from "./ToTop";
import Form from "./Form";
 
 

function Contact() {
  const isDesktopOrLaptop = useMediaQuery({ minDeviceWidth: 1224 });
  
  const isTabletOrMobile = useMediaQuery({ query: "(max-width: 766px)" });
  const themee=useSelector(state=>state.theme)
  return (
    <div>
      {/* <Head>
        <title>{"Tosiron's Portfolio|| Home"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

      {/* <main className="bg-hero-pattern yolo h-screen flex-col"> */}
        <main className={ themee.light ? styles.bodyanimation2 : styles.bodyanimation }>
        <div className={styles.cube}></div>
       <div className={styles.cube}></div>
       <div className={styles.cube}></div>
       <div className={styles.cube}></div>
      <div className={styles.cube}></div>
        {/* sidenav */}
        <div className="flex h-screen w-screen">
        {isTabletOrMobile ? (
          <DrawerComp />
        ) : (
          <div className="ml-1 lg:ml-5 h-full fixed top-40   flex flex-col justify-center items-start">
            
            <Hero />
          </div>
        )}
          <div className=" mx-9 md:ml-40 lg:mx-40 h-auto  m-auto flex flex-col justify-center items-start w-full ">
            <h1 className="text-3xl mt-10 text-yellow-500 md:text-transparent md:bg-clip-text md:bg-gradient-to-r md:from-yellow-200 md:to-yellow-800  lg:text-transparent lg:bg-clip-text lg:bg-gradient-to-r from-yellow-200 to-yellow-800 flex flex-col justify-start font-poppins font-bold items-center">
              Contact
            </h1>
             

            <div className="flex flex-col w-full ">
                
                <div>
                    <Form/>
                     
                </div>
                 
            </div>

          </div>
        </div>
        <ToTop/>
      </main>
    </div>
  );
}


export default Contact