import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>{"Tosiron's Portfolio"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Site Upgrade in Progress....
        </h1>
        <p className={styles.p}>in the meantime, you can check out my <a href="https://github.com/tosibinaronmuro">github</a></p>
        </main>
    </div>
  )
}
